trigger:
- main  # Runs the pipeline when code is pushed to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Uses a Microsoft-hosted agent

steps:
- script: echo "Hello, Azure DevOps Pipeline has been successfully executed!"
  displayName: "Print Success Message"
